# Generated by Django 3.1.1 on 2020-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('office', models.CharField(choices=[('PRE', 'Diretor Presidente'), ('MARK', 'Diretor de Markting'), ('FIN', 'Diretor Finaceiro'), ('INV', 'Diretor de Inovações'), ('RH', 'Diretor de Gestão de Pessoas'), ('DP', 'Diretor de Projetos'), ('DV', 'Desenvolvedor')], max_length=30, verbose_name='Cargo')),
                ('linkdin', models.URLField(max_length=50, verbose_name='Linkedin')),
                ('github', models.URLField(max_length=50, verbose_name='GitHub')),
                ('instagram', models.URLField(max_length=50, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Funcionarios',
            },
        ),
    ]
