# Generated by Django 3.1.1 on 2020-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_worker_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Funcionario'},
        ),
        migrations.AlterField(
            model_name='worker',
            name='office',
            field=models.CharField(choices=[('Diretor Presidente', 'PRE'), ('Diretor de Markting', 'MARK'), ('Diretor Finaceiro', 'FIN'), ('Diretor de Inovações', 'INV'), ('Diretor de Gestão de Pessoas', 'RH'), ('Diretor de Projetos', 'DP'), ('Desenvolvedor', 'DV')], max_length=30, verbose_name='Cargo'),
        ),
    ]
