# Generated by Django 3.1.1 on 2020-10-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201008_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='office',
            field=models.CharField(choices=[('Diretor Presidente', 'DPRE'), ('Diretor de Markting', 'DMARK'), ('Diretor Finaceiro', 'DFIN'), ('Diretor de Inovações', 'DINV'), ('Diretor de Gestão de Pessoas', 'DRH'), ('Diretor de Projetos', 'DPRJ'), ('Desenvolvedor', 'DEV')], max_length=30, verbose_name='Cargo'),
        ),
    ]
