# Generated by Django 3.1.1 on 2020-10-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201008_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='github',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='linkdin',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Linkedin'),
        ),
    ]
