# Generated by Django 3.1.1 on 2020-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201008_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='linkdin',
            field=models.URLField(blank=True, verbose_name='Linkedin'),
        ),
    ]
